name: Automatic Release

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, Linux, X64]

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: recursive
    - name: Setup git
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
    - name: Delete mujs if exists
      run: |
        rm -rf FoxOS-programs/mujs/mujs
    - name: make
      run: |
        make clean -i
        make docker-img vmdk vdi qcow2 sdk
    - name: usb
      run: |
        echo usb | make usb
        zip -r usb.zip usb/*
        zip -r sdk.zip tmp/sdk/*
    - name: screenshot
      run: |
        make screenshot-bios
    - uses:  marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: "latest"
        prerelease: false
        title: "Development Build"
        files: | 
            foxos.img
            foxos.vmdk
            foxos.vdi
            foxos.qcow2
            foxos.jpg
            usb.zip
            sdk.zip
