name: Automatic Release

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: recursive
    - uses: Glowman554/setup-nasm@v1
    - name: install tools
      run: sudo apt install mtools
    - name: make
      run: |
        make img
        echo usb | make usb
        zip -r usb.zip usb/*
    - uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: | 
            foxos.img
            usb.zip
