name: Automatic Release

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, Linux, X64]

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: recursive
    - name: make
      run: |
        make clean -i
        make img vmdk vdi qcow2
        echo usb | make usb
        zip -r usb.zip usb/*
        make screenshot
    - uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: | 
            foxos.img
            foxos.vmdk
            foxos.vdi
            foxos.qcow2
            foxos.jpg
            usb.zip
