name: Automatic Release

on:
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]
  
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: recursive
    - uses: Glowman554/setup-nasm@v1
    - name: setup
      run: sudo apt install mtools
    - name: make
      run: |
        echo usb | make usb
        zip usb.zip usb/*
    - uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: "latest"
        prerelease: false
        title: "Development Build"
        files: usb.zip 
